2023-07-19 14:26:07,436 INFO    MainThread:5838 [wandb_setup.py:_flush():76] Current SDK version is 0.15.5
2023-07-19 14:26:07,436 INFO    MainThread:5838 [wandb_setup.py:_flush():76] Configure stats pid to 5838
2023-07-19 14:26:07,436 INFO    MainThread:5838 [wandb_setup.py:_flush():76] Loading settings from /home/robot-lab/.config/wandb/settings
2023-07-19 14:26:07,436 INFO    MainThread:5838 [wandb_setup.py:_flush():76] Loading settings from /home/robot-lab/Documents/wandb/settings
2023-07-19 14:26:07,436 INFO    MainThread:5838 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-07-19 14:26:07,436 INFO    MainThread:5838 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-07-19 14:26:07,436 INFO    MainThread:5838 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-07-19 14:26:07,436 INFO    MainThread:5838 [wandb_init.py:_log_setup():507] Logging user logs to /home/robot-lab/Documents/wandb/run-20230719_142607-r5hig9zq/logs/debug.log
2023-07-19 14:26:07,436 INFO    MainThread:5838 [wandb_init.py:_log_setup():508] Logging internal logs to /home/robot-lab/Documents/wandb/run-20230719_142607-r5hig9zq/logs/debug-internal.log
2023-07-19 14:26:07,436 INFO    MainThread:5838 [wandb_init.py:init():547] calling init triggers
2023-07-19 14:26:07,436 INFO    MainThread:5838 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-07-19 14:26:07,436 INFO    MainThread:5838 [wandb_init.py:init():571] re-initializing run, found existing run on stack: hhm6acmd
2023-07-19 14:26:07,437 INFO    MainThread:5838 [wandb_run.py:_finish():1887] finishing run paul-nieuwerburgh/BVAE/hhm6acmd
2023-07-19 14:26:07,465 INFO    MainThread:5838 [jupyter.py:save_history():445] not saving jupyter history
2023-07-19 14:26:07,465 INFO    MainThread:5838 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-07-19 14:26:07,465 INFO    MainThread:5838 [wandb_init.py:_jupyter_teardown():435] cleaning up jupyter logic
2023-07-19 14:26:07,465 INFO    MainThread:5838 [wandb_run.py:_atexit_cleanup():2121] got exitcode: 0
2023-07-19 14:26:07,465 INFO    MainThread:5838 [wandb_run.py:_restore():2104] restore
2023-07-19 14:26:07,465 INFO    MainThread:5838 [wandb_run.py:_restore():2110] restore done
2023-07-19 14:26:50,562 INFO    MainThread:5838 [wandb_init.py:init():596] starting backend
2023-07-19 14:26:50,562 INFO    MainThread:5838 [wandb_init.py:init():600] setting up manager
2023-07-19 14:26:50,564 INFO    MainThread:5838 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-07-19 14:26:50,565 INFO    MainThread:5838 [wandb_init.py:init():606] backend started and connected
2023-07-19 14:26:50,569 INFO    MainThread:5838 [wandb_run.py:_label_probe_notebook():1233] probe notebook
2023-07-19 14:26:50,569 INFO    MainThread:5838 [wandb_run.py:_label_probe_notebook():1243] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-07-19 14:26:50,569 INFO    MainThread:5838 [wandb_init.py:init():705] updated telemetry
2023-07-19 14:26:50,570 INFO    MainThread:5838 [wandb_init.py:init():738] communicating run to backend with 60.0 second timeout
2023-07-19 14:27:50,625 ERROR   MainThread:5838 [wandb_init.py:init():764] encountered error: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-07-19 14:27:50,663 ERROR   MainThread:5838 [wandb_init.py:init():1172] Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/home/robot-lab/anaconda3/envs/BVAE/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1154, in init
    run = wi.init()
  File "/home/robot-lab/anaconda3/envs/BVAE/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 770, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
